// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Criação_tabela_NotaFiscal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criação_tabela_NotaFiscal));
        
        string IMigrationMetadata.Id
        {
            get { return "201901260210033_Criação_tabela_NotaFiscal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
