// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<Guid>("NotaFiscalId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CNPJDestinatarioNF")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<string>("CNPJEmissorNF")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<DateTime>("DataNF");

                    b.Property<long>("NumeroNF")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ValorTotal");

                    b.HasKey("NotaFiscalId");

                    b.ToTable("NotaFiscal");
                });
#pragma warning restore 612, 618
        }
    }
}
